language: python
python:
#  - '2.7'
  - '3.6'
  - '3.7'
before_install:
  - sudo apt-get install gfortran
install:
  - pip install --upgrade pytest cython pytest-cov codecov numpy>=1.16
  - python setup.py install

script:
  - python -m pytest -vv --cov=gbm_drm_gen/
  - codecov --token=74fead2f-80bb-45b0-bc40-44a2c80ab9d6
